#!/bin/bash
# Copyright (c) 2026 Wireguard2Home / Gate2Home / https://github.com/wikicell. All rights reserved.

WIREGUARD2HOME_CONFIG_FILE="${WIREGUARD2HOME_CONFIG_FILE:-/etc/wireguard2home.conf}"

if [ -f "$WIREGUARD2HOME_CONFIG_FILE" ]; then
  # Shared runtime overrides for service-user and path configuration.
  # shellcheck disable=SC1090
  . "$WIREGUARD2HOME_CONFIG_FILE"
fi

wireguard2home_resolve_user_home() {
  local user_name="$1"
  if [ -n "${2:-}" ]; then
    printf '%s\n' "$2"
    return
  fi

  local passwd_home=""
  passwd_home="$(getent passwd "$user_name" 2>/dev/null | awk -F: '{print $6}')"
  if [ -n "$passwd_home" ]; then
    printf '%s\n' "$passwd_home"
    return
  fi

  printf '/root\n'
}

WIREGUARD2HOME_SERVICE_USER="${WIREGUARD2HOME_SERVICE_USER:-root}"
WIREGUARD2HOME_SERVICE_HOME="$(wireguard2home_resolve_user_home "$WIREGUARD2HOME_SERVICE_USER" "${WIREGUARD2HOME_SERVICE_HOME:-}")"
WIREGUARD2HOME_BACKUP_SSH_USER="${WIREGUARD2HOME_BACKUP_SSH_USER:-$WIREGUARD2HOME_SERVICE_USER}"
WIREGUARD2HOME_BACKUP_SSH_HOME="$(wireguard2home_resolve_user_home "$WIREGUARD2HOME_BACKUP_SSH_USER" "${WIREGUARD2HOME_BACKUP_SSH_HOME:-}")"
WIREGUARD2HOME_BACKUP_REMOTE_USER="${WIREGUARD2HOME_BACKUP_REMOTE_USER:-root}"
WIREGUARD2HOME_BACKUP_REMOTE_HOME="$(wireguard2home_resolve_user_home "$WIREGUARD2HOME_BACKUP_REMOTE_USER" "${WIREGUARD2HOME_BACKUP_REMOTE_HOME:-}")"

WIREGUARD2HOME_CLIENT_DIR="${WIREGUARD2HOME_CLIENT_DIR:-${WIREGUARD2HOME_SERVICE_HOME}/wg-clients}"
WIREGUARD2HOME_CLIENT_ARCHIVE_PATH="${WIREGUARD2HOME_CLIENT_DIR#/}"

if [ -z "${WIREGUARD2HOME_STATE_DIR:-}" ]; then
  if [ "$WIREGUARD2HOME_SERVICE_USER" = "root" ]; then
    WIREGUARD2HOME_STATE_DIR="/var/lib/gate2home/wg-dashboard"
  else
    WIREGUARD2HOME_STATE_DIR="${WIREGUARD2HOME_SERVICE_HOME}/.local/state/gate2home/wg-dashboard"
  fi
fi

WIREGUARD2HOME_BACKUP_BASE="${WIREGUARD2HOME_BACKUP_BASE:-${WIREGUARD2HOME_SERVICE_HOME}/backups/gate2home}"
WIREGUARD2HOME_PRE_RESTORE_ROOT="${WIREGUARD2HOME_PRE_RESTORE_ROOT:-${WIREGUARD2HOME_SERVICE_HOME}/pre-restore-backups}"
WIREGUARD2HOME_TARGET_SCRIPT="${WIREGUARD2HOME_TARGET_SCRIPT:-${WIREGUARD2HOME_SERVICE_HOME}/Wireguard2Home.sh}"
WIREGUARD2HOME_BACKUP_SSH_KEY="${WIREGUARD2HOME_BACKUP_SSH_KEY:-${WIREGUARD2HOME_BACKUP_SSH_HOME}/.ssh/gate2home_backup}"
WIREGUARD2HOME_BACKUP_REMOTE_HOST="${WIREGUARD2HOME_BACKUP_REMOTE_HOST:-10.100.0.2}"
WIREGUARD2HOME_BACKUP_REMOTE_TARGET="${WIREGUARD2HOME_BACKUP_REMOTE_TARGET:-${WIREGUARD2HOME_BACKUP_REMOTE_HOME}/backups/from-vps}"
WIREGUARD2HOME_DASHBOARD_SCRIPT="${WIREGUARD2HOME_DASHBOARD_SCRIPT:-${WIREGUARD2HOME_SERVICE_HOME}/wireguard-dashboard.sh}"
WIREGUARD2HOME_DNS_HOME_LABEL="${WIREGUARD2HOME_DNS_HOME_LABEL:-Home DNS}"
WIREGUARD2HOME_DNS_HOME_VALUE="${WIREGUARD2HOME_DNS_HOME_VALUE:-192.168.50.53}"
WIREGUARD2HOME_DNS_ROUTER_LABEL="${WIREGUARD2HOME_DNS_ROUTER_LABEL:-Router DNS}"
WIREGUARD2HOME_DNS_ROUTER_VALUE="${WIREGUARD2HOME_DNS_ROUTER_VALUE:-192.168.50.1}"
WIREGUARD2HOME_LAN_SUBNET="${WIREGUARD2HOME_LAN_SUBNET:-192.168.50.0/24}"
WIREGUARD2HOME_ENDPOINT="${WIREGUARD2HOME_ENDPOINT:-vpn.example.com:51820}"
WIREGUARD2HOME_SPEEDTEST_USER="${WIREGUARD2HOME_SPEEDTEST_USER:-$WIREGUARD2HOME_BACKUP_REMOTE_USER}"
WIREGUARD2HOME_SPEEDTEST_HOST="${WIREGUARD2HOME_SPEEDTEST_HOST:-10.100.0.2}"
WIREGUARD2HOME_SPEEDTEST_SSH_KEY="${WIREGUARD2HOME_SPEEDTEST_SSH_KEY:-$WIREGUARD2HOME_BACKUP_SSH_KEY}"
WIREGUARD2HOME_SPEEDTEST_SIZE_MB="${WIREGUARD2HOME_SPEEDTEST_SIZE_MB:-64}"
